### ISSUE TITLE
Добавить v1/server/questions_help возвращающий массив вопросов с ответами

### ISSUE THREAD

**Issue by MixKage** [MixKage/CardExamBackendGO#11]
public class QuestionHelpModels
{
    // Ячейка вопросов для быстрой помощи в приложении
    // Если в вопросе {uri:google.com} то в приложении создаётся кнпока
    // Которая отправит на сайт указанный после двоеточия
    public string Question { get; set; }
    public string Answer { get; set; }
}

**Comment by AlexS778** [comment]
done #9
